Dataset pages
hicsail/signlab-react pull request #4
Opened 2023-08-08 19:23 UTC by ukamila

# Description

> The two pages under Dataset category: Dataset Controls and Project Access are now completed. I would need some guidance on verifying that the uploaded CSV file and uploaded videos fit the format, but other than that, the frontend is ready.

## Checklist

- [ + ] This PR can be reviewed in under 30 minutes
- [ + ] My code follows the style guidelines of this project
- [ + ] I have performed a self-review of my own code
- [ + ] I have commented my code, particularly in hard-to-understand areas
- [ + ] I have made corresponding changes to the documentation
- [ + ] I have assigned reviewers to this PR.

2023-08-09 15:11 UTC, cbolles requested changes
Minor suggestion that should help make the `AddDataset` portion easier

2023-08-09 15:11 UTC, cbolles commented on src/components/AddDataset.tsx
> +  const [name, setName] = useState('');
Since we are already using JSON forms we might as well use it again here. It will handle things like validation and handling changes

2023-08-09 16:07 UTC, ukamila commented
I also found that the font I've been using is not showing correctly in some web browsers, should this be something I look into

2023-08-09 16:18 UTC, cbolles commented
> I also found that the font I've been using is not showing correctly in some web browsers, should this be something I look into

Yea it may just not be included in every browser. You can add it to the top level html file in the header to ensure the font is present

2023-08-09 16:26 UTC, ukamila commented
Which file is that? I don't think I can add font to <App /> or to <ReactDom />

2023-08-09 16:31 UTC, cbolles commented
> Which file is that? I don't think I can add font to or to

Most fonts you can find a URL reference for them. [Here is an example](https://github.com/hicsail/nist-frontend/blob/main/index.html#L7)

2023-08-10 16:24 UTC, ukamila commented
I have added fonts and now it's looking much better

2023-08-10 18:41 UTC, cbolles approved these changes
Looks good!

2023-08-10 20:48 UTC, merged